### ISSUE TITLE
Failed to publish: Unauthorized HTTP Code 401

### ISSUE THREAD

**Issue by Prefinem** [fanout/php-fanout#1]
Whenever I try and publish using PHP, composer, Google App Engine (using purl for curl calls) I get an error

    PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to publish: Unauthorized
    ' in ~/vendor/fanout/pubcontrol/fanout/php-pubcontrol/src/pccutilities.php:55
    Stack trace:
    #0 ~/vendor/fanout/pubcontrol/fanout/php-pubcontrol/src/pccutilities.php(28): PubControl\PccUtilities->verify_http_status_code('Unauthorized\n', 401)
    #1 ~/vendor/fanout/pubcontrol/fanout/php-pubcontrol/src/pubcontrolclient.php(94): PubControl\PccUtilities->pubcall('https://api.fan...', 'Bearer eyJ0eXAi...', Array)

Since I am relatively new to fanout, I am assuming that for some reason, the server is not authorized to make that call?  I am following the docs and just making the call

    $app['fanout']->publish('test', $message);

**Comment by jkarneges** [comment]
I did some testing with purl, and I came across two issues:

1) Header handling is incorrect. Seems there's already bug report here: https://github.com/azayarni/purl/issues/12
2) SSL may be an issue too.

Will investigate further and report back.

**Comment by jkarneges** [comment]
Can you use PHP 5.5? Looks like GAE added support for curl recently:
https://cloud.google.com/appengine/docs/php/#dynamically_loadable_extensions

**Comment by Prefinem** [comment]
Will do.  Thanks for the update.  I was searching for curl for GAE and couldn't find it.  Will report back with the status.

**Comment by Prefinem** [comment]
PHP5.5 with curl enabled works perfectly.  Thanks for the help!
